collections:
  - name: community.general

roles:
- src: gantsign.oh-my-zsh
  version: "2.7.0"
- src: oefenweb.chrome
  version: "v1.0.45"
- src: oefenweb.virtualbox
- src: oefenweb.vagrant
- src: geerlingguy.docker
- src: aeimer.install_bat
- src: andrewrothstein.go
- src: geerlingguy.java
- src: cimon-io.asdf
